# Generated by Django 4.1.6 on 2023-02-21 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extras', '0084_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('quantidade_fibras', models.IntegerField()),
                ('descricao', models.CharField(max_length=60)),
                ('lote_cabo', models.CharField(max_length=50)),
                ('metragem_inicial', models.FloatField()),
                ('metragem_final', models.FloatField()),
                ('total_metragem', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TipoBobina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('descricao', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('metragem_requisitada', models.FloatField()),
                ('data_requisicao', models.DateField(auto_now=True)),
                ('bilhete_associado', models.CharField(max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('nome_fornecedor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.PositiveIntegerField()),
                ('endereco_site', models.CharField(max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('nome_fornecedor',),
            },
        ),
        migrations.CreateModel(
            name='FibraRequisitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('imagem_corte_cabo', models.FileField(upload_to='uploads/')),
                ('bobina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_inventory_fibers.bobina')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_inventory_fibers.requisicao')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='bobina',
            name='nome_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_inventory_fibers.fornecedor'),
        ),
        migrations.AddField(
            model_name='bobina',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='bobina',
            name='tipo_bobina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_inventory_fibers.tipobobina'),
        ),
    ]
