# Generated by Django 4.1.6 on 2023-02-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bobina',
            options={'ordering': ('id',), 'verbose_name': 'Bobinas'},
        ),
        migrations.RemoveField(
            model_name='bobina',
            name='author',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tipobobina',
            name='author',
        ),
    ]
