# Generated by Django 4.1.7 on 2023-02-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='metragem_requisitada',
        ),
        migrations.AddField(
            model_name='fibrarequisitada',
            name='metragem_requisitada',
            field=models.FloatField(default=0),
        ),
    ]
