# Generated by Django 4.1.6 on 2023-02-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='quantidadeFibras',
            field=models.IntegerField(),
        ),
    ]
