# Generated by Django 4.1.6 on 2023-02-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='data_requisicao',
        ),
    ]
