# Generated by Django 4.1.7 on 2023-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0002_remove_requisicao_metragem_requisitada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibrarequisitada',
            old_name='requisicao',
            new_name='id_requisicao',
        ),
        migrations.AddField(
            model_name='bobina',
            name='total_estoque',
            field=models.FloatField(default=0),
        ),
    ]
