# Generated by Django 4.1.7 on 2023-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0005_remove_bobina_total_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobina',
            name='total_estoque',
            field=models.FloatField(default=0),
        ),
    ]
