# Generated by Django 4.1.7 on 2023-02-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0006_bobina_total_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='tipo_bobina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bobinas', to='netbox_inventory_fibers.tipobobina'),
        ),
    ]
