# Generated by Django 4.1.7 on 2023-02-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0008_alter_bobina_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tipobobina',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
