# Generated by Django 4.1.7 on 2023-03-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0009_fornecedor_comments_tipobobina_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobina',
            old_name='descricao',
            new_name='modelo',
        ),
    ]
