# Generated by Django 4.1.7 on 2023-03-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0011_quantidadefibracabo_alter_bobina_quantidade_fibras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bobina',
            options={'ordering': ('id',), 'verbose_name_plural': 'Bobinas'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ('nome_fornecedor',), 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='quantidadefibracabo',
            options={'ordering': ('id',), 'verbose_name': 'Quantidade de Fibra'},
        ),
        migrations.AlterModelOptions(
            name='requisicao',
            options={'ordering': ('id',), 'verbose_name_plural': 'Requisições'},
        ),
    ]
