# Generated by Django 4.1.7 on 2023-03-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0013_rename_id_requisicao_fibrarequisitada_ordem_de_servico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicao',
            options={'ordering': ('id',), 'verbose_name_plural': 'Ordens de Serviço'},
        ),
    ]
