# Generated by Django 4.1.7 on 2023-03-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0014_alter_requisicao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='ordem_de_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fibrarequisitada_to_ordem_servico', to='netbox_inventory_fibers.requisicao'),
        ),
    ]
