# Generated by Django 4.1.7 on 2023-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0015_alter_fibrarequisitada_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='metragem_final',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobina',
            name='metragem_inicial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobina',
            name='total_metragem',
            field=models.FloatField(default=0),
        ),
    ]
