# Generated by Django 4.1.7 on 2023-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0016_alter_bobina_metragem_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobina',
            name='total_estoque',
        ),
    ]
