# Generated by Django 4.1.7 on 2023-03-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0018_bobina_total_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobina',
            old_name='total_metragem',
            new_name='metragem_cadastrada',
        ),
    ]
