# Generated by Django 4.1.7 on 2023-03-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0020_bobina_id_privado_bobina_num_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='id_privado',
            field=models.TextField(default='NA', max_length=50),
        ),
    ]
