# Generated by Django 4.1.7 on 2023-03-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0021_alter_bobina_id_privado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobina',
            name='id_privado',
        ),
        migrations.RemoveField(
            model_name='bobina',
            name='num_auxiliar',
        ),
    ]
