# Generated by Django 4.1.7 on 2023-03-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0024_alter_tipobobina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobina',
            name='num_auxiliar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='bobina',
            field=models.ForeignKey(db_column='lote_cabo', db_index=False, on_delete=django.db.models.deletion.PROTECT, to='netbox_inventory_fibers.bobina'),
        ),
    ]
