# Generated by Django 4.1.7 on 2023-03-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0025_bobina_num_auxiliar_alter_fibrarequisitada_bobina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobina',
            name='num_auxiliar',
        ),
    ]
