# Generated by Django 4.1.7 on 2023-03-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0026_remove_bobina_num_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='bobina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_inventory_fibers.bobina'),
        ),
    ]
