# Generated by Django 4.1.7 on 2023-03-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0027_alter_fibrarequisitada_bobina'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='imagem_OS',
            field=models.ImageField(default='0', unique=True, upload_to='uploads/'),
        ),
    ]
