# Generated by Django 4.1.7 on 2023-03-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0028_requisicao_imagem_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='imagem_corte_cabo',
            field=models.ImageField(unique=True, upload_to='uploads/cortes'),
        ),
    ]
