# Generated by Django 4.1.7 on 2023-03-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0029_alter_fibrarequisitada_imagem_corte_cabo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='imagem_OS',
            field=models.FileField(unique=True, upload_to='uploads/'),
        ),
    ]
