# Generated by Django 4.1.7 on 2023-03-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0030_alter_requisicao_imagem_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='imagem_OS',
            field=models.FileField(unique=True, upload_to='uploads/OS'),
        ),
    ]
