# Generated by Django 4.1.7 on 2023-03-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0031_alter_requisicao_imagem_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobina',
            name='id_privado',
            field=models.TextField(default='NA', max_length=50),
        ),
    ]
