# Generated by Django 4.1.7 on 2023-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0035_alter_fibrarequisitada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='ordem_de_servico',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
