# Generated by Django 4.1.7 on 2023-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0036_alter_requisicao_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='id_customizado',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='ordem_de_servico',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
