# Generated by Django 4.1.7 on 2023-03-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0037_alter_fibrarequisitada_id_customizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobina',
            name='special_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
