# Generated by Django 4.1.7 on 2023-03-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0038_bobina_special_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='special_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
