# Generated by Django 4.1.7 on 2023-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0039_alter_bobina_special_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='metragem_cadastrada',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
