# Generated by Django 4.1.7 on 2023-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0040_alter_bobina_metragem_cadastrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='id_customizado',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
