# Generated by Django 4.1.7 on 2023-03-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0041_alter_fibrarequisitada_id_customizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibrarequisitada',
            name='id_customizado',
            field=models.CharField(default=None, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
