# Generated by Django 4.1.7 on 2023-04-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0042_alter_fibrarequisitada_id_customizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipobobina',
            options={'ordering': ('id',), 'verbose_name_plural': 'Tipos de Bobina'},
        ),
        migrations.RemoveField(
            model_name='bobina',
            name='metragem_final',
        ),
        migrations.RemoveField(
            model_name='bobina',
            name='metragem_inicial',
        ),
        migrations.AddField(
            model_name='bobina',
            name='comments',
            field=models.TextField(default='Bobina adicionada'),
        ),
        migrations.AlterField(
            model_name='bobina',
            name='metragem_cadastrada',
            field=models.FloatField(default=0),
        ),
    ]
