# Generated by Django 4.1.7 on 2023-04-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0043_alter_tipobobina_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='comments',
            field=models.TextField(blank=True, default='Bobina adicionada'),
        ),
    ]
