# Generated by Django 4.1.7 on 2023-04-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0044_alter_bobina_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobina',
            name='reposicao',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobina',
            name='comments',
            field=models.TextField(blank=True, default='Metragem Inicial:\nMetragem Final:'),
        ),
    ]
