# Generated by Django 4.1.7 on 2023-04-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_fibers', '0045_bobina_reposicao_alter_bobina_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobina',
            name='reposicao',
        ),
    ]
